/**
 * The fresh charge-01 codec vs the GOLDEN VECTORS generated by
 * pops-core-verify's own canonical encoders (protocol/vectors/, produced by
 * server/src/bin/gen_vectors.rs at 7e366f0). The byte-identical credential
 * check is the cross-language JCS guarantee.
 */

import { describe, expect, test } from "bun:test";
import { decodePaymentRequest } from "@cashu/cashu-ts";
import vectors from "../../protocol/vectors/charge01-vectors.json";
import {
  assertPayable,
  b64urlDecode,
  buildCredential,
  decodeRequestObject,
  jcsSerialize,
  parsePaymentChallenge,
  problemSlug,
  type PaymentChallenge,
} from "../src/charge01.ts";

const challenge = vectors.challenge as PaymentChallenge;

describe("WWW-Authenticate parsing", () => {
  test("parses the exact header the Rust hosts emit", () => {
    const parsed = parsePaymentChallenge(vectors.wwwAuthenticate);
    expect(parsed.id).toBe(challenge.id);
    expect(parsed.realm).toBe(challenge.realm);
    expect(parsed.method).toBe("cashu");
    expect(parsed.intent).toBe("charge");
    expect(parsed.request).toBe(challenge.request);
    expect(parsed.expires).toBe(challenge.expires!);
    expect(parsed.digest).toBeUndefined();
    expect(parsed.opaque).toBeUndefined();
  });

  test("tolerates reordered/unknown params, missing scheme prefix", () => {
    const shuffled = `request="${challenge.request}", x-future="1", intent="charge", method="cashu", realm="${challenge.realm}", id="${challenge.id}"`;
    const parsed = parsePaymentChallenge(shuffled);
    expect(parsed.id).toBe(challenge.id);
    expect(parsed.expires).toBeUndefined();
  });

  test("rejects unquoted values (mis-binding hazard)", () => {
    expect(() =>
      parsePaymentChallenge(`Payment id=bare, realm="r", method="cashu", intent="charge", request="x"`),
    ).toThrow(/double-quoted/);
  });

  test("rejects a missing required param", () => {
    expect(() =>
      parsePaymentChallenge(`Payment id="a", method="cashu", intent="charge", request="x"`),
    ).toThrow(/missing `realm`/);
  });
});

describe("request object", () => {
  test("decodes the vector byte-for-byte equal to the Rust decoder's view", () => {
    const obj = decodeRequestObject(vectors.requestB64);
    expect(obj).toEqual(vectors.requestObject as typeof obj);
  });

  test("rejects padded base64url (grammar violation)", () => {
    expect(() => decodeRequestObject(vectors.requestB64 + "==")).toThrow(
      /base64url-nopad/,
    );
  });

  test("rejects a request object missing methodDetails.paymentRequest", () => {
    const bogus = Buffer.from(JSON.stringify({ amount: "1", currency: "pop_1" }))
      .toString("base64url");
    expect(() => decodeRequestObject(bogus)).toThrow(/methodDetails/);
  });
});

describe("creqA cross-checks (client MUSTs before paying)", () => {
  const obj = decodeRequestObject(vectors.requestB64);
  const decoded = decodePaymentRequest(obj.methodDetails.paymentRequest);
  const creqa = {
    amount:
      typeof decoded.amount === "number"
        ? decoded.amount
        : (decoded.amount as unknown as { toNumber(): number }).toNumber(),
    unit: decoded.unit ?? "",
    mints: decoded.mints ?? [],
  };

  test("cashu-ts decodes the creqA to the expected facts", () => {
    expect(creqa).toEqual(vectors.creqaDecoded);
  });

  test("a consistent challenge passes", () => {
    expect(() => assertPayable(challenge, obj, creqa)).not.toThrow();
  });

  test("a past expires is refused before paying", () => {
    const stale = { ...challenge, expires: "2020-01-01T00:00:00Z" };
    expect(() => assertPayable(stale, obj, creqa)).toThrow(/expired/);
  });

  test("top-level vs creqA amount mismatch is refused", () => {
    const evil = { ...obj, amount: "51" };
    expect(() => assertPayable(challenge, evil, creqa)).toThrow(/amount/);
  });

  test("currency/unit mismatch is refused", () => {
    const evil = { ...obj, currency: "sat" };
    expect(() => assertPayable(challenge, evil, creqa)).toThrow(/currency/);
  });

  test("an empty mint set is refused", () => {
    expect(() =>
      assertPayable(challenge, obj, { ...creqa, mints: [] }),
    ).toThrow(/mints/);
  });
});

describe("credential building (the JCS cross-language check)", () => {
  test("builds a BYTE-IDENTICAL blob to pops' encode_payment_credentials", () => {
    const header = buildCredential(challenge, vectors.token);
    expect(header).toBe(`Payment ${vectors.credentialBlobB64}`);
  });

  test("no-expires + description variant is also byte-identical", () => {
    const variant = vectors.noExpiresVariant.challenge as PaymentChallenge;
    const header = buildCredential(variant, vectors.token);
    expect(header).toBe(`Payment ${vectors.noExpiresVariant.credentialBlobB64}`);
  });

  test("the blob decodes to a faithful echo (sorted keys, verbatim request)", () => {
    const header = buildCredential(challenge, vectors.token);
    const json = JSON.parse(
      new TextDecoder().decode(b64urlDecode(header.slice("Payment ".length))),
    );
    expect(json.challenge.request).toBe(challenge.request);
    expect(json.challenge.expires).toBe(challenge.expires!);
    expect(json.payload.token).toBe(vectors.token);
    expect(json.source).toBeUndefined();
  });
});

describe("jcs", () => {
  test("sorts keys recursively and omits undefined", () => {
    expect(jcsSerialize({ b: 1, a: { d: "x", c: [true, null] }, z: undefined })).toBe(
      '{"a":{"c":[true,null],"d":"x"},"b":1}',
    );
  });
});

describe("problem slugs", () => {
  test("extracts the slug from an absolute problem type", () => {
    expect(
      problemSlug({ type: "https://paymentauth.org/problems/payment-expired" }),
    ).toBe("payment-expired");
    expect(problemSlug({ type: "about:blank" })).toBe("about:blank");
    expect(problemSlug("nope")).toBeUndefined();
  });
});
