//! Golden-vector generation for the charge-01 codec, produced with
//! pops-core-verify's OWN canonical encoders (the byte-level source of truth).
//!
//! The committed file `../protocol/vectors/charge01-vectors.json` is consumed
//! by BOTH test suites:
//!   - cargo (`tests/vectors_match.rs`): regenerates and diffs — catches a
//!     pops-crate wire change under us;
//!   - bun (`client/test/charge01.test.ts`): asserts the fresh TS codec
//!     parses the challenge/request identically and builds a BYTE-IDENTICAL
//!     credential blob (the JCS cross-language check).
//!
//! Regenerate: `cargo run --bin gen-vectors > ../protocol/vectors/charge01-vectors.json`

use pops_core_verify::binding::{compute_challenge_id, BindingKey, BindingSlots};
use pops_core_verify::challenge::{encode_charge_request, CashuRequirement};
use pops_core_verify::envelope::{
    decode_request_object, encode_payment_credentials, CashuPayload, EchoedChallenge,
    PaymentCredentials,
};
use serde_json::{json, Value};
use std::str::FromStr;

/// Vector constants — frozen, NOT live values (codec tests only).
const VECTOR_UNIT: &str = "pop_1700000000";
const VECTOR_MINT: &str = "http://127.0.0.1:28338";
const VECTOR_REALM: &str = "pops-core-verify"; // the middleware's hardcoded realm
const VECTOR_EXPIRES: &str = "2030-01-01T00:00:00Z"; // future => fresh in tests
const VECTOR_TOKEN: &str = "cashuBnightbazaarvectortoken";
const VECTOR_KEY_HEX: &str = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";

pub fn generate() -> Value {
    let requirement = CashuRequirement {
        unit: cashu::nuts::CurrencyUnit::from_str(VECTOR_UNIT).expect("custom unit parses"),
        mints: vec![cashu::MintUrl::from_str(VECTOR_MINT).expect("mint url parses")],
        amount: cashu::Amount::from(50u64),
        external_id: Some("bazaar:court.jade".to_string()),
        description: Some("Night Bazaar - Jade Court entry".to_string()),
    };
    let request_b64 = encode_charge_request(&requirement).expect("non-empty mints encode");
    let request_object = decode_request_object(&request_b64).expect("own encoding decodes");

    let key = BindingKey::from_hex(VECTOR_KEY_HEX).expect("vector key hex");
    let id = compute_challenge_id(
        &key,
        &BindingSlots {
            realm: VECTOR_REALM,
            method: "cashu",
            intent: "charge",
            request_b64: &request_b64,
            expires: Some(VECTOR_EXPIRES),
            digest: None,
            opaque: None,
        },
    );
    // Header formatted exactly as binding::issue_challenge does.
    let www_authenticate = format!(
        r#"Payment id="{id}", realm="{VECTOR_REALM}", method="cashu", intent="charge", request="{request_b64}", expires="{VECTOR_EXPIRES}""#
    );

    let challenge = EchoedChallenge {
        id: id.clone(),
        realm: VECTOR_REALM.to_string(),
        method: "cashu".to_string(),
        intent: "charge".to_string(),
        request: request_b64.clone(),
        digest: None,
        opaque: None,
        expires: Some(VECTOR_EXPIRES.to_string()),
        description: None,
    };
    let credential_blob = encode_payment_credentials(&PaymentCredentials {
        challenge: challenge.clone(),
        payload: CashuPayload {
            token: VECTOR_TOKEN.to_string(),
        },
        source: None,
    });

    // A second vector without `expires` and WITH a description: exercises the
    // optional-field omission/echo rules of the JCS encoding.
    let id2 = compute_challenge_id(
        &key,
        &BindingSlots {
            realm: VECTOR_REALM,
            method: "cashu",
            intent: "charge",
            request_b64: &request_b64,
            expires: None,
            digest: None,
            opaque: None,
        },
    );
    let challenge2 = EchoedChallenge {
        id: id2.clone(),
        realm: VECTOR_REALM.to_string(),
        method: "cashu".to_string(),
        intent: "charge".to_string(),
        request: request_b64.clone(),
        digest: None,
        opaque: None,
        expires: None,
        description: Some("optional description, echoed verbatim".to_string()),
    };
    let credential_blob2 = encode_payment_credentials(&PaymentCredentials {
        challenge: challenge2,
        payload: CashuPayload {
            token: VECTOR_TOKEN.to_string(),
        },
        source: None,
    });

    json!({
        "comment": "GENERATED by server/src/bin/gen_vectors.rs against pops-core-verify @4ea81e9 — do not hand-edit. Frozen test constants, not live values.",
        "bindingKeyHex": VECTOR_KEY_HEX,
        "requestB64": request_b64,
        "requestObject": {
            "amount": request_object.amount,
            "currency": request_object.currency,
            "description": request_object.description,
            "externalId": request_object.external_id,
            "methodDetails": { "paymentRequest": request_object.method_details.payment_request },
        },
        "creqaDecoded": { "amount": 50, "unit": VECTOR_UNIT, "mints": [VECTOR_MINT] },
        "wwwAuthenticate": www_authenticate,
        "challenge": {
            "id": id,
            "realm": VECTOR_REALM,
            "method": "cashu",
            "intent": "charge",
            "request": request_b64,
            "expires": VECTOR_EXPIRES,
        },
        "token": VECTOR_TOKEN,
        "credentialBlobB64": credential_blob,
        "noExpiresVariant": {
            "challenge": {
                "id": id2,
                "realm": VECTOR_REALM,
                "method": "cashu",
                "intent": "charge",
                "request": request_b64,
                "description": "optional description, echoed verbatim",
            },
            "credentialBlobB64": credential_blob2,
        },
    })
}
